### ISSUE TITLE
FYI: random 'reconnected' message means shutting off notifications basically required

### ISSUE THREAD

**Issue by jspraul** [ausbitbank/stable-diffusion-discord-bot#17]
Is there another way to keep informed of reconnects?

I didn't see any way to send a 'silent' message of any kind, unfortunately.

**Comment by ausbitbank** [comment]
https://github.com/ausbitbank/stable-diffusion-discord-bot/blob/41ec8d251efbf4387529e0d06ac517ec0693eb1a/index.js#L68

To silence it just comment out line 68 or replace with however you'd like to be notified. Maybe there should be a debug/testing mode variable that enables/disables a lot of similar feedback
