### ISSUE TITLE
Feature - docker

### ISSUE THREAD

**Issue by simplesisu** [ausbitbank/stable-diffusion-discord-bot#41]
Thank you for the awesome bot, appreciated!
It would be fantastic to have an installation feature where the Discord bot could be easily deployed as a Docker container.

**Comment by ausbitbank** [comment]
Several users have run the bot in a docker container, it's doable just not something supported out of the box.
You need to setup invokeai seperately, work out how to make the invokeai web api available to your artbot docker, and have a bind mount to your .env bot configuration file and your invokeai output folder.

Here's the basic template for `arty.dockerfile` but the bind mounts and networking are up to you to figure out sorry :P 

```
FROM node:18.13.0-alpine

# Install Git
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone https://github.com/ausbitbank/stable-diffusion-discord-bot /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN npm install

# Install the "forever" utility
RUN npm install -g forever

# Set up a mount point for the database folder
VOLUME /app/database

# Start the application using the "forever" utility
CMD ["forever", "index.js"]
```

**Comment by simplesisu** [comment]
Thanks for the quick reply, I somehow got it to work. When sending a prompt via the discord bot it works, a picture is generated BUT the picture is not shown in discord...In the Invoke Docker container output folder I can find the picture which was generated. From the discord bot container i get this error from the logs:

```
[Error: ENOENT: no such file or directory, open '/mnt/user/SD-Outputs/InvokeAI/03-InvokeAI/output:/app/output000011.ac064d6c.2916674852.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/mnt/user/SD-Outputs/InvokeAI/03-InvokeAI/output:/app/output000011.ac064d6c.2916674852.png'
}

> stable-diffusion-discord-bot@1.0.0 start /app
> node index.js

read schedule db
init schedule
Connected to discord
Guilds: 1
createnewuser called with id 720606954371809342
created new user with id 720606954371809342
sisuuu:A hyper realistic avatar of a redhead girl riding on a black honda cbr 650r in leather suit, no helmet, high detail, high quality,8K,photo realism --width 512 --height 512 --seed 2916674852 --scale 7.5 --sampler ddim --steps 50 --strength 0.75 --n 1 --gfpgan_strength 0 --codeformer_strength 0 --upscale_level  --upscale_strength 0.5 --threshold 0 --perlin 0 --seamless false --hires_fix false --variation_amount 0 --with_variations  --model stable-diffusion-1.5
```

in the .env file I have made the change for this output path and also in the docker-compose.yaml.

.env:

**Comment by simplesisu** [comment]
I will continue troubleshooting, this hard & fun but very time consuming so I understand if you don't have time.

**Comment by ausbitbank** [comment]
The bot can't access the file, and in its error it shows the path including the `:`
 
`open '/mnt/user/SD-Outputs/InvokeAI/03-InvokeAI/output:/app/output000011.ac064d6c.2916674852.png'`

Makes me think theres an issue with the folder mounting, but I don't know the syntax it's supposed to use to help there yet sorry.

Feel free to jump in the discord for help too https://discord.gg/EfNc2ujcQA

**Comment by ausbitbank** [comment]
Ok in the bots .env file under basePath it should say `/app/output/` with the trailing slash , to work with the bind mount you setup

**Comment by simplesisu** [comment]
Thank you for your insightful responses. While the suggestions provided didn't resolve my issue, I truly appreciate your inputs. I'll be taking this feature request to the Unraid forums in hopes that a someone brave enough :D might tackle the challenge and create a Docker container for it!

**Comment by ausbitbank** [comment]
I had another bot user try docker and they ended up getting it working successfully with this:
```
# syntax=docker/dockerfile:1
FROM node:18-bullseye AS builder
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends git && apt-get clean
WORKDIR /build
RUN git clone --separate-git-dir=$(mktemp -u) --depth 1 https://github.com/ausbitbank/stable-diffusion-discord-bot .
# Build dependencies
RUN npm install --omit=dev

FROM node:18-bullseye
# Create app directory
WORKDIR /bot
# Install app dependencies
COPY --from=builder /build/package*.json ./
COPY --from=builder /build/node_modules/ ./node_modules
COPY --from=builder /build/txt/ ./txt
COPY --from=builder /build/index.js ./
COPY --from=builder /build/dbGalleryChannels.json.example dbGalleryChannels.json
COPY --from=builder /build/dbPayments.json.example dbPayments.json
COPY --from=builder /build/dbQueue.json.example dbQueue.json
COPY --from=builder /build/dbSchedule.json.example dbSchedule.json
COPY --from=builder /build/dbUsers.json.example dbUsers.json

VOLUME "/InvokeAI/outputs"

ENTRYPOINT ["node", "-r", "dotenv/config", "index.js"]
```

It still needs to mount in the bots .env file and the invokeai output directory, but otherwise that should work too.
Good luck :)

**Comment by simplesisu** [comment]
Great info! I'll try this out.

**Comment by simplesisu** [comment]
Quick update: 
After a weeks travel plus a week with a sever man cold I've tested the configurations and mappings.....and it works!

Yet again, thanks for the help!
