### ISSUE TITLE
Hive + /recharge crash

### ISSUE THREAD

**Issue by lunamidori5** [ausbitbank/stable-diffusion-discord-bot#56]
Bot crashes if you are using stripe payment and not hive, no easy way to turn off hive in config file? Thank you for the bot! and keep up the great work!

**Comment by ausbitbank** [comment]
That's kinda by design tbh, Hive was always intended as the primary way for taking payments, since there are zero transaction fees at all.. You can get an account via places like http://signup.hive.io/ or message me the username you want on discord and I can send you keys in a few seconds

**Comment by ausbitbank** [comment]
That said, v2 will probably support this. Everything will be modular and redesigned with hive/hive-engine/stripe/tipcc all configurable seperately or not at all
